# Generated by Django 4.0.6 on 2022-11-01 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingAuthor', models.SmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('authorUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Имя категории')),
                ('name_en', models.CharField(max_length=64, null=True, unique=True, verbose_name='Имя категории')),
                ('name_ru', models.CharField(max_length=64, null=True, unique=True, verbose_name='Имя категории')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryType', models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2, verbose_name='Тип контента')),
                ('categoryType_en', models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2, null=True, verbose_name='Тип контента')),
                ('categoryType_ru', models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2, null=True, verbose_name='Тип контента')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dateCreation_en', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('dateCreation_ru', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=128, null=True, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Контент')),
                ('text_en', models.TextField(null=True, verbose_name='Контент')),
                ('text_ru', models.TextField(null=True, verbose_name='Контент')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('rating_en', models.SmallIntegerField(default=0, null=True, verbose_name='Рейтинг')),
                ('rating_ru', models.SmallIntegerField(default=0, null=True, verbose_name='Рейтинг')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Автор')),
                ('author_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Автор')),
                ('author_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('cat_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('cat_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
                ('post_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post')),
                ('post_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('text_en', models.TextField(null=True, verbose_name='Текст комментария')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст комментария')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('dateCreation_en', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата комментария')),
                ('dateCreation_ru', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата комментария')),
                ('rating', models.SmallIntegerField(default=0, verbose_name='Рейтинг')),
                ('rating_en', models.SmallIntegerField(default=0, null=True, verbose_name='Рейтинг')),
                ('rating_ru', models.SmallIntegerField(default=0, null=True, verbose_name='Рейтинг')),
                ('commentPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Пост')),
                ('commentPost_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Пост')),
                ('commentPost_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Пост')),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('commentUser_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('commentUser_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='CategorySubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, through='news.CategorySubscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
