# Generated by Django 4.1 on 2022-09-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_categorysubscribers_category_subscribers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorysubscribers',
            old_name='category_thru',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='categorysubscribers',
            old_name='subscriber_thru',
            new_name='subscriber',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='categoryThrough',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='postThrough',
            new_name='post',
        ),
    ]
